### PR TITLE
Use Foreman::ClientCertificate

### PR DESCRIPTION
**Pull request by ekohl**
Note I didn't test this, but this came up in https://github.com/theforeman/foreman/pull/7402#issuecomment-627126844 and I wanted to show an example in the discussion.

### CODE REVIEW

**Comment by timogoebel** [comment]
Thanks, can you please bump the minimum required foreman version to 2.0 (also in the travis config)? https://github.com/dm-drogeriemarkt/foreman_dlm/blob/ca43f537d62235969fe64494684f0ca4232e8768/lib/foreman_dlm/engine.rb#L26

> Note I didn't test this

CI test coverage should be enough to merge this without manual testing.

**Comment by ekohl** [comment]
Done.

**Comment by timogoebel** [comment]
Looks like the integration tests on travis are broken.
@kamils-iRonin will submit a PR to migrate foreman_dlm to Github Actions. This should fix the issue. We can then rebase this PR on top.

**Comment by timogoebel** [comment]
@ekohl: Do you mind rebasing this?

**Comment by ekohl** [comment]
Rebased. Also simplified the CI to only test on Foreman 2.0

**Comment by timogoebel** [comment]
Thanks, @ekohl.

**Pull request merged**
